#!/bin/sh

betterlockscreen -l blur

export GDK_BACKEND=x11

session=${1:-dwm}
case $session in
	i3|i3wm		) exec i3;;
	gnome		) exec gnome-session;;
	dwm		) exec dwm;;
esac

dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

