
:set mouse=a
syntax enable

scriptencoding utf-8
set encoding=utf-8

set t_Co=64

source ~/.vim/custom/plugins.vim

autocmd FileType java source ~/.vim/custom/java.vim
" autocmd FileType tex source ~/.vim/custom/latex.vim
autocmd FileType py source ~/.vim/custom/python.vim


